name: Publish Master Push Event
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish_event:
    runs-on: ubuntu-latest
    name: Publish staging push
    steps:
      - run: |
          curl -i \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PUBLISH_PUSH_TOKEN }}" \
            https://api.github.com/repos/awalsh128/cache-apt-pkgs-action-ci/dispatches \
            -d '{"event_type":"master_push"}'